import { PluginFunction, PluginValidateFn, Types } from '@graphql-codegen/plugin-helpers'
import { GraphQLSchema, parse, Kind, OperationDefinitionNode } from 'graphql'

export interface ApolloHooksPluginConfig {
  /**
   * Name of the exported hook identifier prefix.
   * @default 'use'
   */
  hookPrefix?: string
  /**
   * Import Apollo hooks from custom location.
   * @default '@apollo/client/react'
   */
  apolloReactImportFrom?: string
  /**
   * Group operations by module/folder.
   * @default true
   */
  groupByModule?: boolean
}

export const validate: PluginValidateFn<ApolloHooksPluginConfig> = async (
  _schema: GraphQLSchema,
  _documents: Types.DocumentFile[],
  config: ApolloHooksPluginConfig,
  _outputFile: string
) => {
  // Validate config here if needed
}

export const plugin: PluginFunction<ApolloHooksPluginConfig> = (
  _schema: GraphQLSchema,
  documents: Types.DocumentFile[],
  config: ApolloHooksPluginConfig
) => {
  const hookPrefix = config.hookPrefix || 'use'
  const importFrom = config.apolloReactImportFrom || '@apollo/client/react'

  // Group operations by module
  const operationsByModule = new Map<string, OperationInfo[]>()

  for (const doc of documents) {
    if (!doc.rawSDL) continue

    const filePath = doc.location || ''
    const moduleName = getModuleName(filePath)

    try {
      const parsedDoc = parse(doc.rawSDL)

      for (const def of parsedDoc.definitions) {
        if (def.kind !== Kind.OPERATION_DEFINITION) continue

        const operation = def as OperationDefinitionNode
        const operationName = operation.name?.value
        if (!operationName) continue

        const isQuery = operation.operation === 'query'
        const isMutation = operation.operation === 'mutation'
        const isSubscription = operation.operation === 'subscription'

        const info: OperationInfo = {
          operationName,
          operationType: operation.operation,
          hookName: getHookName(operationName, hookPrefix, isQuery, isMutation, isSubscription),
          typeName: getTypeName(operationName, isQuery, isMutation, isSubscription),
          variablesTypeName: `${operationName}Variables`,
          isQuery,
          isMutation,
          isSubscription,
        }

        const existing = operationsByModule.get(moduleName) || []
        operationsByModule.set(moduleName, [...existing, info])
      }
    } catch (e) {
      // Skip invalid documents
      console.warn(`Failed to parse document: ${filePath}`, e)
    }
  }

  // Generate output
  let output = `/* eslint-disable */\n`
  output += `/**\n * @graphql-codegen/apollo-hooks\n * Generated by graphql-codegen\n */\n\n`

  // Add imports
  output += `import { useQuery, useMutation, useSubscription } from '${importFrom}'\n\n`

  // Generate hooks by module
  for (const [moduleName, operations] of operationsByModule) {
    if (config.groupByModule !== false) {
      output += `// ============ ${moduleName.toUpperCase()} ============\n\n`
    }

    for (const op of operations) {
      output += generateHook(op) + '\n\n'
    }
  }

  return {
    content: output,
  }
}

interface OperationInfo {
  operationName: string
  operationType: 'query' | 'mutation' | 'subscription'
  hookName: string
  typeName: string
  variablesTypeName: string
  isQuery: boolean
  isMutation: boolean
  isSubscription: boolean
}

function getModuleName(filePath: string): string {
  if (!filePath) return 'global'
  const normalized = filePath.replace(/\\/g, '/')
  const parts = normalized.split('/')
  // Get parent directory name
  if (parts.length >= 2) {
    return parts[parts.length - 2] || 'global'
  }
  return 'global'
}

function getHookName(
  operationName: string,
  prefix: string,
  isQuery: boolean,
  isMutation: boolean,
  isSubscription: boolean
): string {
  // Clean up operation name
  let name = operationName
    .replace(/^(Query|Mutation|Subscription|Get|Set|Create|Update|Delete)/i, '')
    .replace(/Input$/i, '')

  if (isQuery) {
    return `${prefix}${name}Query`
  } else if (isMutation) {
    return `${prefix}${name}Mutation`
  } else if (isSubscription) {
    return `${prefix}${name}Subscription`
  }
  return `${prefix}${name}`
}

function getTypeName(
  operationName: string,
  isQuery: boolean,
  isMutation: boolean,
  isSubscription: boolean
): string {
  if (isQuery) return `${operationName}Query`
  if (isMutation) return `${operationName}Mutation`
  if (isSubscription) return `${operationName}Subscription`
  return operationName
}

function generateHook(op: OperationInfo): string {
  const { hookName, typeName, variablesTypeName, operationName, isQuery, isMutation, isSubscription } = op

  if (isQuery) {
    return `export function ${hookName}(baseOptions?: Parameters<typeof useQuery>[2]) {
  return useQuery<${typeName}, ${variablesTypeName}>(${operationName}Document, baseOptions)
}`
  } else if (isMutation) {
    return `export function ${hookName}(baseOptions?: Parameters<typeof useMutation>[2]) {
  return useMutation<${typeName}, ${variablesTypeName}>(${operationName}Document, baseOptions)
}`
  } else if (isSubscription) {
    return `export function ${hookName}(baseOptions?: Parameters<typeof useSubscription>[2]) {
  return useSubscription<${typeName}, ${variablesTypeName}>(${operationName}Document, baseOptions)
}`
  }
  return ''
}

export default { plugin, validate }
