import { PluginFunction, PluginValidateFn, Types } from '@graphql-codegen/plugin-helpers'
import { GraphQLSchema, parse, Kind, OperationDefinitionNode } from 'graphql'

export interface ApolloHooksPluginConfig {
  /**
   * Name of the exported hook identifier prefix.
   * @default 'use'
   */
  hookPrefix?: string
  /**
   * Import Apollo hooks from custom location.
   * @default '@apollo/client/react'
   */
  apolloReactImportFrom?: string
  /**
   * Group operations by module/folder.
   * @default true
   */
  groupByModule?: boolean
  /**
   * Only generate hooks for this specific module.
   * If set, only operations from this module will be included.
   */
  module?: string
}

export const validate: PluginValidateFn<ApolloHooksPluginConfig> = async (
  _schema: GraphQLSchema,
  _documents: Types.DocumentFile[],
  config: ApolloHooksPluginConfig,
  _outputFile: string
) => {
  // Validate config here if needed
}

export const plugin: PluginFunction<ApolloHooksPluginConfig> = (
  _schema: GraphQLSchema,
  documents: Types.DocumentFile[],
  config: ApolloHooksPluginConfig
) => {
  const hookPrefix = config.hookPrefix || 'use'
  const importFrom = config.apolloReactImportFrom || '@apollo/client/react'
  const targetModule = config.module

  // Group operations by module
  const operationsByModule = new Map<string, OperationInfo[]>()

  for (const doc of documents) {
    if (!doc.rawSDL) continue

    const filePath = doc.location || ''
    const moduleName = getModuleName(filePath)

    // If targetModule is specified, skip documents from other modules
    if (targetModule && moduleName !== targetModule) continue

    try {
      const parsedDoc = parse(doc.rawSDL)

      for (const def of parsedDoc.definitions) {
        if (def.kind !== Kind.OPERATION_DEFINITION) continue

        const operation = def as OperationDefinitionNode
        const operationName = operation.name?.value
        if (!operationName) continue

        const isQuery = operation.operation === 'query'
        const isMutation = operation.operation === 'mutation'
        const isSubscription = operation.operation === 'subscription'

        const info: OperationInfo = {
          operationName,
          operationType: operation.operation,
          hookName: getHookName(operationName, hookPrefix, isQuery, isMutation, isSubscription),
          typeName: getTypeName(operationName, isQuery, isMutation, isSubscription),
          variablesTypeName: `${operationName}${operation.operation.charAt(0).toUpperCase() + operation.operation.slice(1)}Variables`,
          isQuery,
          isMutation,
          isSubscription,
        }

        const existing = operationsByModule.get(moduleName) || []
        // Deduplicate by operationName to avoid duplicate hooks
        if (!existing.some(op => op.operationName === operationName)) {
          operationsByModule.set(moduleName, [...existing, info])
        }
      }
    } catch (e) {
      // Skip invalid documents
      console.warn(`Failed to parse document: ${filePath}`, e)
    }
  }

  // Collect all unique operation info for imports
  const allOperations: OperationInfo[] = []
  const seenOps = new Set<string>()
  for (const ops of operationsByModule.values()) {
    for (const op of ops) {
      if (!seenOps.has(op.operationName)) {
        seenOps.add(op.operationName)
        allOperations.push(op)
      }
    }
  }

  // Generate output
  let output = `/* eslint-disable */\n`
  output += `/**\n * @graphql-codegen/apollo-hooks\n * Generated by graphql-codegen\n */\n\n`

  // Add imports for Apollo hooks
  output += `import { useQuery, useMutation, useSubscription } from '${importFrom}'\n`

  // Add imports for types and documents from graphql file
  if (allOperations.length > 0) {
    const importPath = targetModule ? `@/gql/${targetModule}/graphql` : '@/gql/graphql'
    // Generate list of imports: Document, Mutation/Query type, Variables
    const imports: string[] = []
    for (const op of allOperations) {
      imports.push(op.operationName + 'Document')
      imports.push(op.typeName)
      imports.push(op.variablesTypeName)
    }
    // Sort and deduplicate
    const sortedImports = [...new Set(imports)].sort()
    output += `import { ${sortedImports.join(', ')} } from '${importPath}'\n`
  }

  output += '\n'

  // If targetModule is specified, only output that module's operations
  if (targetModule) {
    const operations = operationsByModule.get(targetModule) || []
    for (const op of operations) {
      output += generateHook(op) + '\n\n'
    }
  } else {
    // Generate hooks by module
    for (const [moduleName, operations] of operationsByModule) {
      if (config.groupByModule !== false) {
        output += `// ============ ${moduleName.toUpperCase()} ============\n\n`
      }

      for (const op of operations) {
        output += generateHook(op) + '\n\n'
      }
    }
  }

  return {
    content: output,
  }
}

interface OperationInfo {
  operationName: string
  operationType: 'query' | 'mutation' | 'subscription'
  hookName: string
  typeName: string
  variablesTypeName: string
  isQuery: boolean
  isMutation: boolean
  isSubscription: boolean
}

function getModuleName(filePath: string): string {
  if (!filePath) return 'global'
  const normalized = filePath.replace(/\\/g, '/')
  const parts = normalized.split('/')
  // Get parent directory name
  if (parts.length >= 2) {
    return parts[parts.length - 2] || 'global'
  }
  return 'global'
}

function getHookName(
  operationName: string,
  prefix: string,
  isQuery: boolean,
  isMutation: boolean,
  isSubscription: boolean
): string {
  // Use full operation name to avoid collisions
  // e.g., CreateComment, UpdateComment, DeleteComment all get unique hook names
  const name = operationName

  if (isQuery) {
    return `${prefix}${name}Query`
  } else if (isMutation) {
    return `${prefix}${name}Mutation`
  } else if (isSubscription) {
    return `${prefix}${name}Subscription`
  }
  return `${prefix}${name}`
}

function getTypeName(
  operationName: string,
  isQuery: boolean,
  isMutation: boolean,
  isSubscription: boolean
): string {
  if (isQuery) return `${operationName}Query`
  if (isMutation) return `${operationName}Mutation`
  if (isSubscription) return `${operationName}Subscription`
  return operationName
}

function generateHook(op: OperationInfo): string {
  const { hookName, typeName, variablesTypeName, operationName, isQuery, isMutation, isSubscription } = op

  if (isQuery) {
    return `export function ${hookName}(baseOptions?: any) {
  return useQuery<${typeName}, ${variablesTypeName}>(${operationName}Document, baseOptions)
}`
  } else if (isMutation) {
    return `export function ${hookName}(baseOptions?: any) {
  return useMutation<${typeName}, ${variablesTypeName}>(${operationName}Document, baseOptions)
}`
  } else if (isSubscription) {
    return `export function ${hookName}(baseOptions?: any) {
  return useSubscription<${typeName}, ${variablesTypeName}>(${operationName}Document, baseOptions)
}`
  }
  return ''
}

export default { plugin, validate }
